# Generated by Django 4.2.3 on 2023-08-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_distrito_escuela_fiscal_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escuela',
            new_name='Establecimiento',
        ),
    ]
